apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-deployment
  labels:
    purpose: ingress-demo
    project: roboshop
    app: app1
spec:
  replicas: 2
  selector:
    matchLabels:
      purpose: ingress-demo
      project: roboshop
      app: app1
  template:
    metadata:
      labels:
        purpose: ingress-demo
        project: roboshop
        app: app1
    spec:
      containers:
        - name: pod1
          image: chaitanyavamsi/app1:v1
---
apiVersion: v1
kind: Service
metadata:
  name: app1-svc
spec:
  selector:
    purpose: ingress-demo
    project: roboshop
    app: app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
